"""
explainability_agent.py

Generates an executive decision report
explaining WHY the recommendation was made.
"""

import time

from agents.base_agent import BaseAgent

from models.execution_context import ExecutionContext
from models.agent_result import AgentResult
from models.explainability import ExplainabilityReport


class ExplainabilityAgent(BaseAgent):

    @property
    def name(self):
        return "ExplainabilityAgent"

    @property
    def description(self):
        return "Generates executive explainability reports."

    def execute(self, context):

        start = time.perf_counter()

        weak = context.context_data["weak_signal_report"]

        risk = context.context_data["risk_report"]

        recommendation = context.context_data["recommendation_report"]

        key_risks = []

        evidence = []

        for signal in weak.signals:

            key_risks.append(signal.signal.value)

            for ev in signal.evidence:

                evidence.append(ev.text)

        report = ExplainabilityReport(

            executive_summary=(
                f"{risk.operational_health.value} operational state "
                f"detected requiring "
                f"{recommendation.priority.value} priority response."
            ),

            operational_health=risk.operational_health.value,

            overall_risk_score=risk.overall_risk_score,

            overall_risk_level=risk.overall_risk_level.value,

            key_risks=key_risks,

            supporting_evidence=evidence,

            recommendation_summary=recommendation.summary,

            affected_business_functions=risk.affected_functions,

            business_impact=risk.estimated_business_impact,

            recovery_estimate=risk.estimated_recovery_time,

            reasoning=(

                "The recommendation was generated by combining "

                "detected operational signals, "

                "enterprise risk scoring, "

                "and business continuity policies."

            )

        )

        context.context_data["explainability_report"] = report

        elapsed = (
            time.perf_counter() - start
        ) * 1000

        result = AgentResult(

            agent_name=self.name,

            status="SUCCESS",

            execution_time_ms=elapsed,

            message="Explainability report generated.",

            data={

                "risk_level": report.overall_risk_level,

                "business_impact": report.business_impact,

                "recovery": report.recovery_estimate

            }

        )

        context.agent_results.append(result)

        return result