"""
recommendation.py

Structured Crisis Response Plan generated by the
RecommendationAgent.
"""

from typing import List
from enum import Enum

from pydantic import BaseModel


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecommendationReport(BaseModel):

    title: str

    priority: Priority

    confidence: float

    summary: str

    immediate_actions: List[str]

    short_term_actions: List[str]

    long_term_actions: List[str]

    stakeholders_to_notify: List[str]

    business_continuity_actions: List[str]

    expected_business_outcome: str